# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 082727012bbf1e2054abf7a1eb75313c807c985aba66dcf1bab12ce2ef3921e746a7a01bb1104707cdd0ad680428d1a09aed503831bea287d9c9049e63d63bc7

test:
  secret_key_base: 0ff4f78f08444af413b79d09b25b088f5772b3cc0b14ba80224cc5c82d50075df135a9b44b1dbd9ddaf5198d15d784c89b183ee72dc3c1f16ed1ec54dff8f86a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
